version: '3.7'

services:
    server:
        build:
            context: ./docker/server/.
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
        links:
            - db
    db:
        image: mariadb
        environment:
            MYSQL_DATABASE: bakery
            MYSQL_USER: baker
            MYSQL_PASSWORD: baker
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql